In [1]:
!pip install pandas
!pip install matplotlib

Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.12/site-packages (3.10.1)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.2.4)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [2]:
# Import necessary libraries
import pandas as pd

# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(dataset_url)

# Display the first few rows
print(df.head())

   ResponseId                      MainBranch                 Age  \
0           1  I am a developer by profession  Under 18 years old
1           2  I am a developer by profession     35-44 years old
2           3  I am a developer by profession     45-54 years old
3           4           I am learning to code     18-24 years old
4           5  I am a developer by profession     18-24 years old

            Employment RemoteWork   Check  \
0  Employed, full-time     Remote  Apples
1  Employed, full-time     Remote  Apples
2  Employed, full-time     Remote  Apples
3   Student, full-time        NaN  Apples
4   Student, full-time        NaN  Apples

                                    CodingActivities  \
0                                              Hobby
1  Hobby;Contribute to open-source projects;Other...
2  Hobby;Contribute to open-source projects;Other...
3                                                NaN
4                                                NaN

                                             EdLevel  \
0                          Primary/elementary school
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3  Some college/university study without earning ...
4  Secondary school (e.g. American high school, G...

                                           LearnCode  \
0                             Books / Physical media
1  Books / Physical media;Colleague;On the job tr...
2  Books / Physical media;Colleague;On the job tr...
3  Other online resources (e.g., videos, blogs, f...
4  Other online resources (e.g., videos, blogs, f...

                                     LearnCodeOnline  ... JobSatPoints_6  \
0                                                NaN  ...            NaN
1  Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2  Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3  Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4  Technical documentation;Blogs;Written Tutorial...  ...            NaN

  JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0            NaN            NaN            NaN             NaN
1            0.0            0.0            0.0             0.0
2            NaN            NaN            NaN             NaN
3            NaN            NaN            NaN             NaN
4            NaN            NaN            NaN             NaN

  JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly JobSat
0             NaN                    NaN        NaN                 NaN    NaN
1             0.0                    NaN        NaN                 NaN    NaN
2             NaN  Appropriate in length       Easy                 NaN    NaN
3             NaN               Too long       Easy                 NaN    NaN
4             NaN              Too short       Easy                 NaN    NaN

[5 rows x 114 columns]

In [3]:
#Summarize the dataset by displaying the column data types, counts, and missing values.¶
# Step 1: Display column data types and non-null counts
print("\nBasic Info:")
print(df.info())

# Step 2: Count missing values per column
missing_values = df.isnull().sum()

# Step 3: Create a summary table
summary_df = pd.DataFrame({
    'Data Type': df.dtypes,
    'Non-Null Count': df.count(),
    'Missing Values': missing_values
})

print("\nDataset Summary:")
print(summary_df)

Basic Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(13), int64(1), object(100)
memory usage: 56.9+ MB
None

Dataset Summary:
                    Data Type  Non-Null Count  Missing Values
ResponseId              int64           65437               0
MainBranch             object           65437               0
Age                    object           65437               0
Employment             object           65437               0
RemoteWork             object           54806           10631
...                       ...             ...             ...
JobSatPoints_11       float64           29445           35992
SurveyLength           object           56182            9255
SurveyEase             object           56238            9199
ConvertedCompYearly   float64           23435           42002
JobSat                float64           29126           36311

[114 rows x 3 columns]

In [4]:
#Generate basic statistics for numerical columns.
# Generate basic statistics for numerical columns
stats = df.describe()

print("\nBasic Statistics for Numerical Columns:")
print(stats)

Basic Statistics for Numerical Columns:
         ResponseId      CompTotal       WorkExp  JobSatPoints_1  \
count  65437.000000   3.374000e+04  29658.000000    29324.000000
mean   32719.000000  2.963841e+145     11.466957       18.581094
std    18890.179119  5.444117e+147      9.168709       25.966221
min        1.000000   0.000000e+00      0.000000        0.000000
25%    16360.000000   6.000000e+04      4.000000        0.000000
50%    32719.000000   1.100000e+05      9.000000       10.000000
75%    49078.000000   2.500000e+05     16.000000       22.000000
max    65437.000000  1.000000e+150     50.000000      100.000000

       JobSatPoints_4  JobSatPoints_5  JobSatPoints_6  JobSatPoints_7  \
count    29393.000000    29411.000000    29450.000000     29448.00000
mean         7.522140       10.060857       24.343232        22.96522
std         18.422661       21.833836       27.089360        27.01774
min          0.000000        0.000000        0.000000         0.00000
25%          0.000000        0.000000        0.000000         0.00000
50%          0.000000        0.000000       20.000000        15.00000
75%          5.000000       10.000000       30.000000        30.00000
max        100.000000      100.000000      100.000000       100.00000

       JobSatPoints_8  JobSatPoints_9  JobSatPoints_10  JobSatPoints_11  \
count    29456.000000    29456.000000     29450.000000     29445.000000
mean        20.278165       16.169432        10.955713         9.953948
std         26.108110       24.845032        22.906263        21.775652
min          0.000000        0.000000         0.000000         0.000000
25%          0.000000        0.000000         0.000000         0.000000
50%         10.000000        5.000000         0.000000         0.000000
75%         25.000000       20.000000        10.000000        10.000000
max        100.000000      100.000000       100.000000       100.000000

       ConvertedCompYearly        JobSat
count         2.343500e+04  29126.000000
mean          8.615529e+04      6.935041
std           1.867570e+05      2.088259
min           1.000000e+00      0.000000
25%           3.271200e+04      6.000000
50%           6.500000e+04      7.000000
75%           1.079715e+05      8.000000
max           1.625660e+07     10.000000

In [5]:
#Identify inconsistent or irrelevant entries in specific columns (e.g., Country).
# Step 1: View unique values in the Country column
print("Unique Country Entries:")
print(df['Country'].unique())

# Step 2: Identify inconsistent formats (e.g., different spellings of the same country)
df['Country'] = df['Country'].str.strip().str.lower()  # Normalize case and spaces

# Step 3: Standardize known country names
corrections = {
    'usa': 'United States',
    'united states': 'United States',
    'u.s.': 'United States',
    'canada': 'Canada',
    'germany': 'Germany',
    'germany ': 'Germany'  # Handling potential trailing spaces
}

df['Country'] = df['Country'].replace(corrections)

# Step 4: Identify irrelevant values (e.g., 'N/A', 'Unknown')
irrelevant_values = ['n/a', 'unknown', 'not specified', 'null', 'other']
df['Country'] = df['Country'].apply(lambda x: None if x in irrelevant_values else x)

# Step 5: Display cleaned values
print("\nCleaned Country Entries:")
print(df['Country'].unique())

Unique Country Entries:
['United States of America'
 'United Kingdom of Great Britain and Northern Ireland' 'Canada' 'Norway'
 'Uzbekistan' 'Serbia' 'Poland' 'Philippines' 'Bulgaria' 'Switzerland'
 'India' 'Germany' 'Ireland' 'Italy' 'Ukraine' 'Australia' 'Brazil'
 'Japan' 'Austria' 'Iran, Islamic Republic of...' 'France' 'Saudi Arabia'
 'Romania' 'Turkey' 'Nepal' 'Algeria' 'Sweden' 'Netherlands' 'Croatia'
 'Pakistan' 'Czech Republic' 'Republic of North Macedonia' 'Finland'
 'Slovakia' 'Russian Federation' 'Greece' 'Israel' 'Belgium' 'Mexico'
 'United Republic of Tanzania' 'Hungary' 'Argentina' 'Portugal'
 'Sri Lanka' 'Latvia' 'China' 'Singapore' 'Lebanon' 'Spain' 'South Africa'
 'Lithuania' 'Viet Nam' 'Dominican Republic' 'Indonesia' 'Kosovo'
 'Morocco' 'Taiwan' 'Georgia' 'San Marino' 'Tunisia' 'Bangladesh'
 'Nigeria' 'Liechtenstein' 'Denmark' 'Ecuador' 'Malaysia' 'Albania'
 'Azerbaijan' 'Chile' 'Ghana' 'Peru' 'Bolivia' 'Egypt' 'Luxembourg'
 'Montenegro' 'Cyprus' 'Paraguay' 'Kazakhstan' 'Slovenia' 'Jordan'
 'Venezuela, Bolivarian Republic of...' 'Costa Rica' 'Jamaica' 'Thailand'
 'Nicaragua' 'Myanmar' 'Republic of Korea' 'Rwanda'
 'Bosnia and Herzegovina' 'Benin' 'El Salvador' 'Zimbabwe' 'Afghanistan'
 'Estonia' 'Malta' 'Uruguay' 'Belarus' 'Colombia' 'Republic of Moldova'
 'Isle of Man' 'Nomadic' 'New Zealand' 'Palestine' 'Armenia'
 'United Arab Emirates' 'Maldives' 'Ethiopia' 'Fiji' 'Guatemala' 'Uganda'
 'Turkmenistan' 'Mauritius' 'Kenya' 'Cuba' 'Gabon' 'Bahamas' 'South Korea'
 'Iceland' 'Honduras' 'Hong Kong (S.A.R.)'
 "Lao People's Democratic Republic" 'Mongolia' 'Cambodia' 'Madagascar'
 'Angola' 'Democratic Republic of the Congo' 'Syrian Arab Republic' 'Iraq'
 'Namibia' 'Senegal' 'Kyrgyzstan' 'Zambia' 'Swaziland' "Côte d'Ivoire"
 'Kuwait' 'Tajikistan' 'Burundi' 'Trinidad and Tobago' 'Mauritania'
 'Sierra Leone' 'Panama' 'Somalia' 'North Korea' 'Dominica' 'Guyana'
 'Togo' 'Oman' 'Barbados' 'Andorra'
 "Democratic People's Republic of Korea" 'Qatar' 'Sudan' 'Cameroon'
 'Papua New Guinea' 'Bahrain' 'Yemen' 'Malawi' 'Burkina Faso'
 'Congo, Republic of the...' 'Botswana' 'Guinea-Bissau' 'Mozambique'
 'Central African Republic' 'Equatorial Guinea' 'Suriname' 'Belize'
 'Libyan Arab Jamahiriya' 'Cape Verde' 'Brunei Darussalam' 'Bhutan'
 'Guinea' 'Niger' 'Antigua and Barbuda' 'Mali' 'Samoa' 'Lesotho'
 'Saint Kitts and Nevis' 'Monaco' 'Micronesia, Federated States of...'
 'Haiti' nan 'Nauru' 'Liberia' 'Chad' 'Djibouti' 'Solomon Islands']

Cleaned Country Entries:
['united states of america'
 'united kingdom of great britain and northern ireland' 'Canada' 'norway'
 'uzbekistan' 'serbia' 'poland' 'philippines' 'bulgaria' 'switzerland'
 'india' 'Germany' 'ireland' 'italy' 'ukraine' 'australia' 'brazil'
 'japan' 'austria' 'iran, islamic republic of...' 'france' 'saudi arabia'
 'romania' 'turkey' 'nepal' 'algeria' 'sweden' 'netherlands' 'croatia'
 'pakistan' 'czech republic' 'republic of north macedonia' 'finland'
 'slovakia' 'russian federation' 'greece' 'israel' 'belgium' 'mexico'
 'united republic of tanzania' 'hungary' 'argentina' 'portugal'
 'sri lanka' 'latvia' 'china' 'singapore' 'lebanon' 'spain' 'south africa'
 'lithuania' 'viet nam' 'dominican republic' 'indonesia' 'kosovo'
 'morocco' 'taiwan' 'georgia' 'san marino' 'tunisia' 'bangladesh'
 'nigeria' 'liechtenstein' 'denmark' 'ecuador' 'malaysia' 'albania'
 'azerbaijan' 'chile' 'ghana' 'peru' 'bolivia' 'egypt' 'luxembourg'
 'montenegro' 'cyprus' 'paraguay' 'kazakhstan' 'slovenia' 'jordan'
 'venezuela, bolivarian republic of...' 'costa rica' 'jamaica' 'thailand'
 'nicaragua' 'myanmar' 'republic of korea' 'rwanda'
 'bosnia and herzegovina' 'benin' 'el salvador' 'zimbabwe' 'afghanistan'
 'estonia' 'malta' 'uruguay' 'belarus' 'colombia' 'republic of moldova'
 'isle of man' 'nomadic' 'new zealand' 'palestine' 'armenia'
 'united arab emirates' 'maldives' 'ethiopia' 'fiji' 'guatemala' 'uganda'
 'turkmenistan' 'mauritius' 'kenya' 'cuba' 'gabon' 'bahamas' 'south korea'
 'iceland' 'honduras' 'hong kong (s.a.r.)'
 "lao people's democratic republic" 'mongolia' 'cambodia' 'madagascar'
 'angola' 'democratic republic of the congo' 'syrian arab republic' 'iraq'
 'namibia' 'senegal' 'kyrgyzstan' 'zambia' 'swaziland' "côte d'ivoire"
 'kuwait' 'tajikistan' 'burundi' 'trinidad and tobago' 'mauritania'
 'sierra leone' 'panama' 'somalia' 'north korea' 'dominica' 'guyana'
 'togo' 'oman' 'barbados' 'andorra'
 "democratic people's republic of korea" 'qatar' 'sudan' 'cameroon'
 'papua new guinea' 'bahrain' 'yemen' 'malawi' 'burkina faso'
 'congo, republic of the...' 'botswana' 'guinea-bissau' 'mozambique'
 'central african republic' 'equatorial guinea' 'suriname' 'belize'
 'libyan arab jamahiriya' 'cape verde' 'brunei darussalam' 'bhutan'
 'guinea' 'niger' 'antigua and barbuda' 'mali' 'samoa' 'lesotho'
 'saint kitts and nevis' 'monaco' 'micronesia, federated states of...'
 'haiti' nan 'nauru' 'liberia' 'chad' 'djibouti' 'solomon islands']

In [6]:
#Standardize entries in columns like Country or EdLevel by mapping inconsistent values to a consistent format.
df['Country'] = df['Country'].str.strip().str.lower()

# Step 2: Define a mapping dictionary for standardization
country_mapping = {
    'usa': 'United States',
    'united states': 'United States',
    'u.s.': 'United States',
    'canada': 'Canada',
    'germany': 'Germany',
    'germany ': 'Germany',  # Handling potential extra spaces
    'france': 'France'
}

# Step 3: Apply the mapping
df['Country'] = df['Country'].replace(country_mapping)

# Step 4: Handle missing or irrelevant values
irrelevant_values = ['n/a', 'unknown', 'not specified', 'null', 'other']
df['Country'] = df['Country'].apply(lambda x: None if x in irrelevant_values else x)

# Step 5: Display cleaned values
print("\nCleaned Country Entries:")
print(df['Country'].unique())

# Optional: Display cleaned DataFrame
print("\nUpdated DataFrame:")
print(df)

Cleaned Country Entries:
['united states of america'
 'united kingdom of great britain and northern ireland' 'Canada' 'norway'
 'uzbekistan' 'serbia' 'poland' 'philippines' 'bulgaria' 'switzerland'
 'india' 'Germany' 'ireland' 'italy' 'ukraine' 'australia' 'brazil'
 'japan' 'austria' 'iran, islamic republic of...' 'France' 'saudi arabia'
 'romania' 'turkey' 'nepal' 'algeria' 'sweden' 'netherlands' 'croatia'
 'pakistan' 'czech republic' 'republic of north macedonia' 'finland'
 'slovakia' 'russian federation' 'greece' 'israel' 'belgium' 'mexico'
 'united republic of tanzania' 'hungary' 'argentina' 'portugal'
 'sri lanka' 'latvia' 'china' 'singapore' 'lebanon' 'spain' 'south africa'
 'lithuania' 'viet nam' 'dominican republic' 'indonesia' 'kosovo'
 'morocco' 'taiwan' 'georgia' 'san marino' 'tunisia' 'bangladesh'
 'nigeria' 'liechtenstein' 'denmark' 'ecuador' 'malaysia' 'albania'
 'azerbaijan' 'chile' 'ghana' 'peru' 'bolivia' 'egypt' 'luxembourg'
 'montenegro' 'cyprus' 'paraguay' 'kazakhstan' 'slovenia' 'jordan'
 'venezuela, bolivarian republic of...' 'costa rica' 'jamaica' 'thailand'
 'nicaragua' 'myanmar' 'republic of korea' 'rwanda'
 'bosnia and herzegovina' 'benin' 'el salvador' 'zimbabwe' 'afghanistan'
 'estonia' 'malta' 'uruguay' 'belarus' 'colombia' 'republic of moldova'
 'isle of man' 'nomadic' 'new zealand' 'palestine' 'armenia'
 'united arab emirates' 'maldives' 'ethiopia' 'fiji' 'guatemala' 'uganda'
 'turkmenistan' 'mauritius' 'kenya' 'cuba' 'gabon' 'bahamas' 'south korea'
 'iceland' 'honduras' 'hong kong (s.a.r.)'
 "lao people's democratic republic" 'mongolia' 'cambodia' 'madagascar'
 'angola' 'democratic republic of the congo' 'syrian arab republic' 'iraq'
 'namibia' 'senegal' 'kyrgyzstan' 'zambia' 'swaziland' "côte d'ivoire"
 'kuwait' 'tajikistan' 'burundi' 'trinidad and tobago' 'mauritania'
 'sierra leone' 'panama' 'somalia' 'north korea' 'dominica' 'guyana'
 'togo' 'oman' 'barbados' 'andorra'
 "democratic people's republic of korea" 'qatar' 'sudan' 'cameroon'
 'papua new guinea' 'bahrain' 'yemen' 'malawi' 'burkina faso'
 'congo, republic of the...' 'botswana' 'guinea-bissau' 'mozambique'
 'central african republic' 'equatorial guinea' 'suriname' 'belize'
 'libyan arab jamahiriya' 'cape verde' 'brunei darussalam' 'bhutan'
 'guinea' 'niger' 'antigua and barbuda' 'mali' 'samoa' 'lesotho'
 'saint kitts and nevis' 'monaco' 'micronesia, federated states of...'
 'haiti' nan 'nauru' 'liberia' 'chad' 'djibouti' 'solomon islands']

Updated DataFrame:
       ResponseId                      MainBranch                 Age  \
0               1  I am a developer by profession  Under 18 years old
1               2  I am a developer by profession     35-44 years old
2               3  I am a developer by profession     45-54 years old
3               4           I am learning to code     18-24 years old
4               5  I am a developer by profession     18-24 years old
...           ...                             ...                 ...
65432       65433  I am a developer by profession     18-24 years old
65433       65434  I am a developer by profession     25-34 years old
65434       65435  I am a developer by profession     25-34 years old
65435       65436  I am a developer by profession     18-24 years old
65436       65437     I code primarily as a hobby     18-24 years old

                Employment                            RemoteWork   Check  \
0      Employed, full-time                                Remote  Apples
1      Employed, full-time                                Remote  Apples
2      Employed, full-time                                Remote  Apples
3       Student, full-time                                   NaN  Apples
4       Student, full-time                                   NaN  Apples
...                    ...                                   ...     ...
65432  Employed, full-time                                Remote  Apples
65433  Employed, full-time                                Remote  Apples
65434  Employed, full-time                             In-person  Apples
65435  Employed, full-time  Hybrid (some remote, some in-person)  Apples
65436   Student, full-time                                   NaN  Apples

                                        CodingActivities  \
0                                                  Hobby
1      Hobby;Contribute to open-source projects;Other...
2      Hobby;Contribute to open-source projects;Other...
3                                                    NaN
4                                                    NaN
...                                                  ...
65432                      Hobby;School or academic work
65433           Hobby;Contribute to open-source projects
65434                                              Hobby
65435  Hobby;Contribute to open-source projects;Profe...
65436                                                NaN

                                                 EdLevel  \
0                              Primary/elementary school
1           Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3      Some college/university study without earning ...
4      Secondary school (e.g. American high school, G...
...                                                  ...
65432       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65433                                                NaN
65434       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65435  Secondary school (e.g. American high school, G...
65436                                                NaN

                                               LearnCode  \
0                                 Books / Physical media
1      Books / Physical media;Colleague;On the job tr...
2      Books / Physical media;Colleague;On the job tr...
3      Other online resources (e.g., videos, blogs, f...
4      Other online resources (e.g., videos, blogs, f...
...                                                  ...
65432  On the job training;School (i.e., University, ...
65433                                                NaN
65434  Other online resources (e.g., videos, blogs, f...
65435  On the job training;Other online resources (e....
65436                                                NaN

                                         LearnCodeOnline  ... JobSatPoints_6  \
0                                                    NaN  ...            NaN
1      Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2      Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3      Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4      Technical documentation;Blogs;Written Tutorial...  ...            NaN
...                                                  ...  ...            ...
65432                                                NaN  ...            NaN
65433                                                NaN  ...            NaN
65434  Technical documentation;Stack Overflow;Social ...  ...            NaN
65435  Technical documentation;Blogs;Written Tutorial...  ...            0.0
65436                                                NaN  ...            NaN

      JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0                NaN            NaN            NaN             NaN
1                0.0            0.0            0.0             0.0
2                NaN            NaN            NaN             NaN
3                NaN            NaN            NaN             NaN
4                NaN            NaN            NaN             NaN
...              ...            ...            ...             ...
65432            NaN            NaN            NaN             NaN
65433            NaN            NaN            NaN             NaN
65434            NaN            NaN            NaN             NaN
65435            0.0            0.0            0.0             0.0
65436            NaN            NaN            NaN             NaN

      JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly  \
0                 NaN                    NaN        NaN                 NaN
1                 0.0                    NaN        NaN                 NaN
2                 NaN  Appropriate in length       Easy                 NaN
3                 NaN               Too long       Easy                 NaN
4                 NaN              Too short       Easy                 NaN
...               ...                    ...        ...                 ...
65432             NaN                    NaN        NaN                 NaN
65433             NaN                    NaN        NaN                 NaN
65434             NaN                    NaN        NaN                 NaN
65435             0.0                    NaN        NaN                 NaN
65436             NaN                    NaN        NaN                 NaN

      JobSat
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
...      ...
65432    NaN
65433    NaN
65434    NaN
65435    NaN
65436    NaN

[65437 rows x 114 columns]

In [7]:
#Encode the Employment column using one-hot encoding.
# Step 1: Handle missing values (fill with 'Unknown')
df['Employment'].fillna('Unknown', inplace=True)

# Step 2: Apply one-hot encoding
df_encoded = pd.get_dummies(df, columns=['Employment'], prefix='Emp')

# Step 3: Display the transformed DataFrame
print("\nOne-Hot Encoded DataFrame:")
print(df_encoded)

/tmp/ipykernel_896/896182538.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Employment'].fillna('Unknown', inplace=True)

One-Hot Encoded DataFrame:
       ResponseId                      MainBranch                 Age  \
0               1  I am a developer by profession  Under 18 years old
1               2  I am a developer by profession     35-44 years old
2               3  I am a developer by profession     45-54 years old
3               4           I am learning to code     18-24 years old
4               5  I am a developer by profession     18-24 years old
...           ...                             ...                 ...
65432       65433  I am a developer by profession     18-24 years old
65433       65434  I am a developer by profession     25-34 years old
65434       65435  I am a developer by profession     25-34 years old
65435       65436  I am a developer by profession     18-24 years old
65436       65437     I code primarily as a hobby     18-24 years old

                                 RemoteWork   Check  \
0                                    Remote  Apples
1                                    Remote  Apples
2                                    Remote  Apples
3                                       NaN  Apples
4                                       NaN  Apples
...                                     ...     ...
65432                                Remote  Apples
65433                                Remote  Apples
65434                             In-person  Apples
65435  Hybrid (some remote, some in-person)  Apples
65436                                   NaN  Apples

                                        CodingActivities  \
0                                                  Hobby
1      Hobby;Contribute to open-source projects;Other...
2      Hobby;Contribute to open-source projects;Other...
3                                                    NaN
4                                                    NaN
...                                                  ...
65432                      Hobby;School or academic work
65433           Hobby;Contribute to open-source projects
65434                                              Hobby
65435  Hobby;Contribute to open-source projects;Profe...
65436                                                NaN

                                                 EdLevel  \
0                              Primary/elementary school
1           Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3      Some college/university study without earning ...
4      Secondary school (e.g. American high school, G...
...                                                  ...
65432       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65433                                                NaN
65434       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65435  Secondary school (e.g. American high school, G...
65436                                                NaN

                                               LearnCode  \
0                                 Books / Physical media
1      Books / Physical media;Colleague;On the job tr...
2      Books / Physical media;Colleague;On the job tr...
3      Other online resources (e.g., videos, blogs, f...
4      Other online resources (e.g., videos, blogs, f...
...                                                  ...
65432  On the job training;School (i.e., University, ...
65433                                                NaN
65434  Other online resources (e.g., videos, blogs, f...
65435  On the job training;Other online resources (e....
65436                                                NaN

                                         LearnCodeOnline  \
0                                                    NaN
1      Technical documentation;Blogs;Books;Written Tu...
2      Technical documentation;Blogs;Books;Written Tu...
3      Stack Overflow;How-to videos;Interactive tutorial
4      Technical documentation;Blogs;Written Tutorial...
...                                                  ...
65432                                                NaN
65433                                                NaN
65434  Technical documentation;Stack Overflow;Social ...
65435  Technical documentation;Blogs;Written Tutorial...
65436                                                NaN

                                                 TechDoc  ...  \
0                                                    NaN  ...
1      API document(s) and/or SDK document(s);User gu...  ...
2      API document(s) and/or SDK document(s);User gu...  ...
3                                                    NaN  ...
4      API document(s) and/or SDK document(s);User gu...  ...
...                                                  ...  ...
65432                                                NaN  ...
65433                                                NaN  ...
65434  API document(s) and/or SDK document(s);AI-powe...  ...
65435  API document(s) and/or SDK document(s);User gu...  ...
65436                                                NaN  ...

      Emp_Student, full-time;Not employed, but looking for work;Not employed, and not looking for work;Student, part-time  \
0                                                  False
1                                                  False
2                                                  False
3                                                  False
4                                                  False
...                                                  ...
65432                                              False
65433                                              False
65434                                              False
65435                                              False
65436                                              False

      Emp_Student, full-time;Not employed, but looking for work;Retired  \
0                                                  False
1                                                  False
2                                                  False
3                                                  False
4                                                  False
...                                                  ...
65432                                              False
65433                                              False
65434                                              False
65435                                              False
65436                                              False

      Emp_Student, full-time;Not employed, but looking for work;Student, part-time  \
0                                                  False
1                                                  False
2                                                  False
3                                                  False
4                                                  False
...                                                  ...
65432                                              False
65433                                              False
65434                                              False
65435                                              False
65436                                              False

      Emp_Student, full-time;Retired  \
0                              False
1                              False
2                              False
3                              False
4                              False
...                              ...
65432                          False
65433                          False
65434                          False
65435                          False
65436                          False

      Emp_Student, full-time;Student, part-time  \
0                                         False
1                                         False
2                                         False
3                                         False
4                                         False
...                                         ...
65432                                     False
65433                                     False
65434                                     False
65435                                     False
65436                                     False

      Emp_Student, full-time;Student, part-time;Employed, part-time  \
0                                                  False
1                                                  False
2                                                  False
3                                                  False
4                                                  False
...                                                  ...
65432                                              False
65433                                              False
65434                                              False
65435                                              False
65436                                              False

      Emp_Student, full-time;Student, part-time;Retired  \
0                                                 False
1                                                 False
2                                                 False
3                                                 False
4                                                 False
...                                                 ...
65432                                             False
65433                                             False
65434                                             False
65435                                             False
65436                                             False

      Emp_Student, part-time Emp_Student, part-time;Employed, part-time  \
0                      False                                      False
1                      False                                      False
2                      False                                      False
3                      False                                      False
4                      False                                      False
...                      ...                                        ...
65432                  False                                      False
65433                  False                                      False
65434                  False                                      False
65435                  False                                      False
65436                  False                                      False

      Emp_Student, part-time;Retired
0                              False
1                              False
2                              False
3                              False
4                              False
...                              ...
65432                          False
65433                          False
65434                          False
65435                          False
65436                          False

[65437 rows x 223 columns]

In [8]:
# Identify columns with the highest number of missing values.
# Count missing values per column
missing_values = df.isnull().sum()

# Sort columns by highest missing values
missing_values_sorted = missing_values.sort_values(ascending=False)

# Display the results
print("\nColumns with Missing Values (Sorted):")
print(missing_values_sorted)

Columns with Missing Values (Sorted):
AINextMuch less integrated    64289
AINextLess integrated         63082
AINextNo change               52939
AINextMuch more integrated    51999
EmbeddedAdmired               48704
                              ...
MainBranch                        0
Age                               0
Employment                        0
Check                             0
ResponseId                        0
Length: 114, dtype: int64

In [9]:
# Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.
# Step 1: Check missing values before imputation
print("\nMissing Values Before Imputation:")
print(df.isnull().sum())

# Step 2: Impute missing values with the median
median_value = df['ConvertedCompYearly'].median()
df['ConvertedCompYearly'].fillna(median_value, inplace=True)

# Step 3: Check missing values after imputation
print("\nMissing Values After Imputation:")
print(df.isnull().sum())

# Step 4: Display updated DataFrame
print("\nUpdated DataFrame:")
print(df)

Missing Values Before Imputation:
ResponseId                 0
MainBranch                 0
Age                        0
Employment                 0
RemoteWork             10631
                       ...
JobSatPoints_11        35992
SurveyLength            9255
SurveyEase              9199
ConvertedCompYearly    42002
JobSat                 36311
Length: 114, dtype: int64

Missing Values After Imputation:

/tmp/ipykernel_896/1528041951.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ConvertedCompYearly'].fillna(median_value, inplace=True)

ResponseId                 0
MainBranch                 0
Age                        0
Employment                 0
RemoteWork             10631
                       ...
JobSatPoints_11        35992
SurveyLength            9255
SurveyEase              9199
ConvertedCompYearly        0
JobSat                 36311
Length: 114, dtype: int64

Updated DataFrame:
       ResponseId                      MainBranch                 Age  \
0               1  I am a developer by profession  Under 18 years old
1               2  I am a developer by profession     35-44 years old
2               3  I am a developer by profession     45-54 years old
3               4           I am learning to code     18-24 years old
4               5  I am a developer by profession     18-24 years old
...           ...                             ...                 ...
65432       65433  I am a developer by profession     18-24 years old
65433       65434  I am a developer by profession     25-34 years old
65434       65435  I am a developer by profession     25-34 years old
65435       65436  I am a developer by profession     18-24 years old
65436       65437     I code primarily as a hobby     18-24 years old

                Employment                            RemoteWork   Check  \
0      Employed, full-time                                Remote  Apples
1      Employed, full-time                                Remote  Apples
2      Employed, full-time                                Remote  Apples
3       Student, full-time                                   NaN  Apples
4       Student, full-time                                   NaN  Apples
...                    ...                                   ...     ...
65432  Employed, full-time                                Remote  Apples
65433  Employed, full-time                                Remote  Apples
65434  Employed, full-time                             In-person  Apples
65435  Employed, full-time  Hybrid (some remote, some in-person)  Apples
65436   Student, full-time                                   NaN  Apples

                                        CodingActivities  \
0                                                  Hobby
1      Hobby;Contribute to open-source projects;Other...
2      Hobby;Contribute to open-source projects;Other...
3                                                    NaN
4                                                    NaN
...                                                  ...
65432                      Hobby;School or academic work
65433           Hobby;Contribute to open-source projects
65434                                              Hobby
65435  Hobby;Contribute to open-source projects;Profe...
65436                                                NaN

                                                 EdLevel  \
0                              Primary/elementary school
1           Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3      Some college/university study without earning ...
4      Secondary school (e.g. American high school, G...
...                                                  ...
65432       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65433                                                NaN
65434       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65435  Secondary school (e.g. American high school, G...
65436                                                NaN

                                               LearnCode  \
0                                 Books / Physical media
1      Books / Physical media;Colleague;On the job tr...
2      Books / Physical media;Colleague;On the job tr...
3      Other online resources (e.g., videos, blogs, f...
4      Other online resources (e.g., videos, blogs, f...
...                                                  ...
65432  On the job training;School (i.e., University, ...
65433                                                NaN
65434  Other online resources (e.g., videos, blogs, f...
65435  On the job training;Other online resources (e....
65436                                                NaN

                                         LearnCodeOnline  ... JobSatPoints_6  \
0                                                    NaN  ...            NaN
1      Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2      Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3      Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4      Technical documentation;Blogs;Written Tutorial...  ...            NaN
...                                                  ...  ...            ...
65432                                                NaN  ...            NaN
65433                                                NaN  ...            NaN
65434  Technical documentation;Stack Overflow;Social ...  ...            NaN
65435  Technical documentation;Blogs;Written Tutorial...  ...            0.0
65436                                                NaN  ...            NaN

      JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0                NaN            NaN            NaN             NaN
1                0.0            0.0            0.0             0.0
2                NaN            NaN            NaN             NaN
3                NaN            NaN            NaN             NaN
4                NaN            NaN            NaN             NaN
...              ...            ...            ...             ...
65432            NaN            NaN            NaN             NaN
65433            NaN            NaN            NaN             NaN
65434            NaN            NaN            NaN             NaN
65435            0.0            0.0            0.0             0.0
65436            NaN            NaN            NaN             NaN

      JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly  \
0                 NaN                    NaN        NaN             65000.0
1                 0.0                    NaN        NaN             65000.0
2                 NaN  Appropriate in length       Easy             65000.0
3                 NaN               Too long       Easy             65000.0
4                 NaN              Too short       Easy             65000.0
...               ...                    ...        ...                 ...
65432             NaN                    NaN        NaN             65000.0
65433             NaN                    NaN        NaN             65000.0
65434             NaN                    NaN        NaN             65000.0
65435             0.0                    NaN        NaN             65000.0
65436             NaN                    NaN        NaN             65000.0

      JobSat
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
...      ...
65432    NaN
65433    NaN
65434    NaN
65435    NaN
65436    NaN

[65437 rows x 114 columns]

In [10]:
# Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.
# Step 1: Identify the most frequent (mode) value in 'RemoteWork'
mode_value = df['RemoteWork'].mode()[0]  # Get the most common value

# Step 2: Fill missing values with the mode
df['RemoteWork'].fillna(mode_value, inplace=True)

# Step 3: Verify missing values are filled
print("\nMissing Values After Imputation:")
print(df.isnull().sum())

# Step 4: Display updated DataFrame
print("\nUpdated DataFrame:")
print(df)

/tmp/ipykernel_896/1885020805.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['RemoteWork'].fillna(mode_value, inplace=True)

Missing Values After Imputation:
ResponseId                 0
MainBranch                 0
Age                        0
Employment                 0
RemoteWork                 0
                       ...
JobSatPoints_11        35992
SurveyLength            9255
SurveyEase              9199
ConvertedCompYearly        0
JobSat                 36311
Length: 114, dtype: int64

Updated DataFrame:
       ResponseId                      MainBranch                 Age  \
0               1  I am a developer by profession  Under 18 years old
1               2  I am a developer by profession     35-44 years old
2               3  I am a developer by profession     45-54 years old
3               4           I am learning to code     18-24 years old
4               5  I am a developer by profession     18-24 years old
...           ...                             ...                 ...
65432       65433  I am a developer by profession     18-24 years old
65433       65434  I am a developer by profession     25-34 years old
65434       65435  I am a developer by profession     25-34 years old
65435       65436  I am a developer by profession     18-24 years old
65436       65437     I code primarily as a hobby     18-24 years old

                Employment                            RemoteWork   Check  \
0      Employed, full-time                                Remote  Apples
1      Employed, full-time                                Remote  Apples
2      Employed, full-time                                Remote  Apples
3       Student, full-time  Hybrid (some remote, some in-person)  Apples
4       Student, full-time  Hybrid (some remote, some in-person)  Apples
...                    ...                                   ...     ...
65432  Employed, full-time                                Remote  Apples
65433  Employed, full-time                                Remote  Apples
65434  Employed, full-time                             In-person  Apples
65435  Employed, full-time  Hybrid (some remote, some in-person)  Apples
65436   Student, full-time  Hybrid (some remote, some in-person)  Apples

                                        CodingActivities  \
0                                                  Hobby
1      Hobby;Contribute to open-source projects;Other...
2      Hobby;Contribute to open-source projects;Other...
3                                                    NaN
4                                                    NaN
...                                                  ...
65432                      Hobby;School or academic work
65433           Hobby;Contribute to open-source projects
65434                                              Hobby
65435  Hobby;Contribute to open-source projects;Profe...
65436                                                NaN

                                                 EdLevel  \
0                              Primary/elementary school
1           Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3      Some college/university study without earning ...
4      Secondary school (e.g. American high school, G...
...                                                  ...
65432       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65433                                                NaN
65434       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65435  Secondary school (e.g. American high school, G...
65436                                                NaN

                                               LearnCode  \
0                                 Books / Physical media
1      Books / Physical media;Colleague;On the job tr...
2      Books / Physical media;Colleague;On the job tr...
3      Other online resources (e.g., videos, blogs, f...
4      Other online resources (e.g., videos, blogs, f...
...                                                  ...
65432  On the job training;School (i.e., University, ...
65433                                                NaN
65434  Other online resources (e.g., videos, blogs, f...
65435  On the job training;Other online resources (e....
65436                                                NaN

                                         LearnCodeOnline  ... JobSatPoints_6  \
0                                                    NaN  ...            NaN
1      Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2      Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3      Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4      Technical documentation;Blogs;Written Tutorial...  ...            NaN
...                                                  ...  ...            ...
65432                                                NaN  ...            NaN
65433                                                NaN  ...            NaN
65434  Technical documentation;Stack Overflow;Social ...  ...            NaN
65435  Technical documentation;Blogs;Written Tutorial...  ...            0.0
65436                                                NaN  ...            NaN

      JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0                NaN            NaN            NaN             NaN
1                0.0            0.0            0.0             0.0
2                NaN            NaN            NaN             NaN
3                NaN            NaN            NaN             NaN
4                NaN            NaN            NaN             NaN
...              ...            ...            ...             ...
65432            NaN            NaN            NaN             NaN
65433            NaN            NaN            NaN             NaN
65434            NaN            NaN            NaN             NaN
65435            0.0            0.0            0.0             0.0
65436            NaN            NaN            NaN             NaN

      JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly  \
0                 NaN                    NaN        NaN             65000.0
1                 0.0                    NaN        NaN             65000.0
2                 NaN  Appropriate in length       Easy             65000.0
3                 NaN               Too long       Easy             65000.0
4                 NaN              Too short       Easy             65000.0
...               ...                    ...        ...                 ...
65432             NaN                    NaN        NaN             65000.0
65433             NaN                    NaN        NaN             65000.0
65434             NaN                    NaN        NaN             65000.0
65435             0.0                    NaN        NaN             65000.0
65436             NaN                    NaN        NaN             65000.0

      JobSat
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
...      ...
65432    NaN
65433    NaN
65434    NaN
65435    NaN
65436    NaN

[65437 rows x 114 columns]

In [11]:
#Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.
from sklearn.preprocessing import MinMaxScaler

In [12]:
# Step 1: Initialize MinMaxScaler
scaler = MinMaxScaler()

# Step 2: Apply Min-Max Scaling to 'ConvertedCompYearly'
df['ConvertedCompYearly_MinMax'] = scaler.fit_transform(df[['ConvertedCompYearly']])

# Step 3: Display the updated DataFrame
print("\nNormalized Data:")
print(df)

Normalized Data:
       ResponseId                      MainBranch                 Age  \
0               1  I am a developer by profession  Under 18 years old
1               2  I am a developer by profession     35-44 years old
2               3  I am a developer by profession     45-54 years old
3               4           I am learning to code     18-24 years old
4               5  I am a developer by profession     18-24 years old
...           ...                             ...                 ...
65432       65433  I am a developer by profession     18-24 years old
65433       65434  I am a developer by profession     25-34 years old
65434       65435  I am a developer by profession     25-34 years old
65435       65436  I am a developer by profession     18-24 years old
65436       65437     I code primarily as a hobby     18-24 years old

                Employment                            RemoteWork   Check  \
0      Employed, full-time                                Remote  Apples
1      Employed, full-time                                Remote  Apples
2      Employed, full-time                                Remote  Apples
3       Student, full-time  Hybrid (some remote, some in-person)  Apples
4       Student, full-time  Hybrid (some remote, some in-person)  Apples
...                    ...                                   ...     ...
65432  Employed, full-time                                Remote  Apples
65433  Employed, full-time                                Remote  Apples
65434  Employed, full-time                             In-person  Apples
65435  Employed, full-time  Hybrid (some remote, some in-person)  Apples
65436   Student, full-time  Hybrid (some remote, some in-person)  Apples

                                        CodingActivities  \
0                                                  Hobby
1      Hobby;Contribute to open-source projects;Other...
2      Hobby;Contribute to open-source projects;Other...
3                                                    NaN
4                                                    NaN
...                                                  ...
65432                      Hobby;School or academic work
65433           Hobby;Contribute to open-source projects
65434                                              Hobby
65435  Hobby;Contribute to open-source projects;Profe...
65436                                                NaN

                                                 EdLevel  \
0                              Primary/elementary school
1           Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3      Some college/university study without earning ...
4      Secondary school (e.g. American high school, G...
...                                                  ...
65432       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65433                                                NaN
65434       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65435  Secondary school (e.g. American high school, G...
65436                                                NaN

                                               LearnCode  \
0                                 Books / Physical media
1      Books / Physical media;Colleague;On the job tr...
2      Books / Physical media;Colleague;On the job tr...
3      Other online resources (e.g., videos, blogs, f...
4      Other online resources (e.g., videos, blogs, f...
...                                                  ...
65432  On the job training;School (i.e., University, ...
65433                                                NaN
65434  Other online resources (e.g., videos, blogs, f...
65435  On the job training;Other online resources (e....
65436                                                NaN

                                         LearnCodeOnline  ... JobSatPoints_7  \
0                                                    NaN  ...            NaN
1      Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2      Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3      Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4      Technical documentation;Blogs;Written Tutorial...  ...            NaN
...                                                  ...  ...            ...
65432                                                NaN  ...            NaN
65433                                                NaN  ...            NaN
65434  Technical documentation;Stack Overflow;Social ...  ...            NaN
65435  Technical documentation;Blogs;Written Tutorial...  ...            0.0
65436                                                NaN  ...            NaN

      JobSatPoints_8 JobSatPoints_9 JobSatPoints_10 JobSatPoints_11  \
0                NaN            NaN             NaN             NaN
1                0.0            0.0             0.0             0.0
2                NaN            NaN             NaN             NaN
3                NaN            NaN             NaN             NaN
4                NaN            NaN             NaN             NaN
...              ...            ...             ...             ...
65432            NaN            NaN             NaN             NaN
65433            NaN            NaN             NaN             NaN
65434            NaN            NaN             NaN             NaN
65435            0.0            0.0             0.0             0.0
65436            NaN            NaN             NaN             NaN

                SurveyLength SurveyEase ConvertedCompYearly JobSat  \
0                        NaN        NaN             65000.0    NaN
1                        NaN        NaN             65000.0    NaN
2      Appropriate in length       Easy             65000.0    NaN
3                   Too long       Easy             65000.0    NaN
4                  Too short       Easy             65000.0    NaN
...                      ...        ...                 ...    ...
65432                    NaN        NaN             65000.0    NaN
65433                    NaN        NaN             65000.0    NaN
65434                    NaN        NaN             65000.0    NaN
65435                    NaN        NaN             65000.0    NaN
65436                    NaN        NaN             65000.0    NaN

      ConvertedCompYearly_MinMax
0                       0.003998
1                       0.003998
2                       0.003998
3                       0.003998
4                       0.003998
...                          ...
65432                   0.003998
65433                   0.003998
65434                   0.003998
65435                   0.003998
65436                   0.003998

[65437 rows x 115 columns]

In [13]:
#Log-transform the ConvertedCompYearly column to reduce skewness.
import pandas as pd
import numpy as np

In [15]:
# Step 1: Apply Log Transformation
df['ConvertedCompYearly_Log'] = np.log(df['ConvertedCompYearly'] + 1)

# Step 2: Display the transformed DataFrame
print("\nLog-Transformed Compensation:")
print(df[['ConvertedCompYearly', 'ConvertedCompYearly_Log']])

Log-Transformed Compensation:
       ConvertedCompYearly  ConvertedCompYearly_Log
0                  65000.0                11.082158
1                  65000.0                11.082158
2                  65000.0                11.082158
3                  65000.0                11.082158
4                  65000.0                11.082158
...                    ...                      ...
65432              65000.0                11.082158
65433              65000.0                11.082158
65434              65000.0                11.082158
65435              65000.0                11.082158
65436              65000.0                11.082158

[65437 rows x 2 columns]

In [23]:
#Create a new column `ExperienceLevel` based on the `YearsCodePro` column:
# Function to classify experience levels
def classify_experience(years):
    if years <= 2:
        return 'Entry-level'
    elif years <= 5:
        return 'Junior'
    elif years <= 10:
        return 'Mid-level'
    elif years <= 15:
        return 'Senior'
    else:
        return 'Expert'

try:
  i = int(i)
except ValueError as err:
  pass 

# Apply function to create the ExperienceLevel column
df['ExperienceLevel'] = df['YearsCodePro'].apply(classify_experience)

# Display updated DataFrame
print("\nUpdated DataFrame with Experience Levels:")
print(df)

TypeError: '<=' not supported between instances of 'str' and 'int'